name: Prepare test data

on:
    push:
        branches:
            - xenium_ci_example
    workflow_dispatch:

jobs:
    prepare-data:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Download test datasets
              run: |
                  mkdir -p ./data
                  cd ./data
                  curl -O https://cf.10xgenomics.com/samples/xenium/2.0.0/Xenium_V1_human_Breast_2fov/Xenium_V1_human_Breast_2fov_outs.zip
                  curl -O https://cf.10xgenomics.com/samples/xenium/2.0.0/Xenium_V1_human_Lung_2fov/Xenium_V1_human_Lung_2fov_outs.zip

            - name: Unzip files
              run: |
                  unzip ./data/Xenium_V1_human_Breast_2fov_outs.zip -d ./data/Xenium_V1_human_Breast_2fov_outs
                  unzip ./data/Xenium_V1_human_Lung_2fov_outs.zip -d ./data/Xenium_V1_human_Lung_2fov_outs

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: data
                  path: ./data
